service: anand-serverless-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket:
    name: cohort5.deployment

functions:
  firstfunction:
    handler: index.firsthandler #entry point of this function
    events:
      - httpApi:
          path: /anandget
          method: get
      - sqs:
          arn: arn:aws:sqs:us-east-1:255945442255:anand-sqs

  secondfunction:
    handler: index.secondhandler #entry point of this function
    events:
      - httpApi:
          path: /anandpost
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - AnandQueue
              - Arn
  
resources:
  Resources:
    AnandQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "anand-queue"

plugins:
  - serverless-offline
